cask_args appdir: "/Applications"

brew "gh"
brew "jq"
brew "mas"
brew "mysql-client"
brew "tcptraceroute"
brew "terminal-notifier"
brew "tfenv"
brew "tmux"
brew "tree"
brew "ripgrep"
brew "neovim"
brew "prettier"
brew "mas"
brew "node@14"
brew "node@16"
brew "php"
brew "php@7.4"
brew "php@8.0"
brew "python@3.8"
brew "python@3.10"
brew "typescript"
brew "zinit"
brew "romkatv/powerlevel10k/powerlevel10k"
brew "exa"
brew "zsh-syntax-highlighting"
brew "bat"
brew "peco"
brew "docker-compose"
brew "nvm"
brew "yarn"
brew "composer"
brew "zsh-autosuggestions"
brew "golangci-lint"
brew "mockery"
brew "gomodifytags"
brew "grc"
brew "act"
brew "watchman"
brew "hyper"
brew "direnv"
brew "rustup-init"
brew "luarocks"
brew "dnsmasq"
brew "dive"
brew "docker-slim"
brew "silicon"
brew "mold"
brew "fd"
brew "gnupg"
brew "hyperfine"
brew "protobuf"
brew "cmake"
brew "wget"

# Go
brew "gopls"
brew "go@1.18"

cask "alfred"
cask "appcleaner"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "mysqlworkbench"
cask "visual-studio-code"
cask "dbeaver-community"
cask "dash"
cask "anki"
cask "ngrok"
cask "neovide"
cask "hammerspoon"
cask "dbeaver-community"
cask "discord"
cask "slack"
cask "kindle"
cask "deepl"
cask "dropbox"
cask "google-cloud-sdk"
cask "figma"
cask "microsoft-edge"
cask "zoom"
cask "krisp"
cask "steam"
cask "devtoys"
cask "1password"
cask "keep"
cask "grammarly"
cask "vrew"
cask "telegram"
cask "rectangle"
cask "alacritty"
cask "spotify"
cask "vivaldi"
cask "betterdummy"
cask "betterdisplay"
cask "miniforge"
cask "keycastr"
cask "diffusionbee"
cask "gulp"
cask "google-cloud-sdk"
cask "telegram"
cask "cursor"

# WezTerm
tap "wez/wezterm"
cask "wez/wezterm/wezterm"

tap "homebrew/cask-fonts"
cask "font-hack-nerd-font"

mas 'Dashlane', id: 517914548
mas 'Line', id: 539883307
mas 'HotspotShield VPN - Wifi Proxy', id: 771076721
mas 'xcode', id: 497799835
