cask_args appdir: "/Applications"

brew "gh"
brew "jq"
brew "mas"
brew "mysql-client"
brew "tcptraceroute"
brew "terminal-notifier"
brew "tfenv"
brew "tmux"
brew "tree"
brew "ripgrep"
brew "neovim"

cask "alfred"
cask "appcleaner"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "mysqlworkbench"
cask "visual-studio-code"
cask "dbeaver-community"
cask "dash"
cask "homebrew/cask/anki"
cask "ngrok"

